#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/bspwm/bin/launchbar.sh

## 144HZ configuration
##if ! xrandr | grep -q 'HDMI-0' ; then
##    bspc config pointer_motion_interval 7
##fi

bspc config pointer_motion_interval 7

## emulates i3 gaps' smart gaps config
bspc config single_monocle true


#workspaces() {
#	name=1
#	for monitor in `bspc query -M`; do
#		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' '漣'
#		let name++
#	done
#}


bspc monitor DP-2 -d '' '' '' '' '' '' '漣'
bspc monitor HDMI-0 -d ' ' '' ''


#workspaces() {
#	name=1
#	for monitor in `bspc query -M`; do
#		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '漣'
#		let name++
#	done
#}

#workspaces_2() {
#	name=2
#	for monitor in `bspc query -M`; do
#		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '漣'
#		let name++
#	done
#}




#workspaces

#workspaces_2

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}



bspc config border_width         2
bspc config window_gap           6
bspc config split_ratio          0.50

#bspc config focused_border_color "#7aa2f7"
#bspc config normal_border_color "#32344a"
#bspc config active_border_color "#444b6a"
#

# aura theme
#bspc config active_border_color "#edecee"
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#61ffca"
#bspc config presel_feedback_color "#6272a4"
#bspc config normal_border_color "#21202e"


# dracula theme
#bspc config normal_border_color "#44475a"
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"
#bspc config presel_feedback_color "#6272a4"


# red theme
#bspc config normal_border_color "#44475a"
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#c80f10"
#bspc config presel_feedback_color "#6272a4"

# layan
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#5657F5"
#bspc config presel_feedback_color "#6272a4"
#bspc config normal_border_color "#44475a"


# grubvox
#bspc config active_border_color "#cc241d"
#bspc config focused_border_color "#5657F"
##bspc config focused_border_color "#c8271e"
#bspc config presel_feedback_color "#b8bb26"
#bspc config normal_border_color "#44475a"

#  synthwave

#bspc config focused_border_color "#35e3f0"
#bspc config active_border_color "#495495"
#bspc config presel_feedback_color "#03edf9"
#bspc config normal_border_color "#21202e"
# andromeda

#bspc config focused_border_color "#00e8c6"
#bspc config active_border_color "#23262E"
#bspc config presel_feedback_color "#03edf9"
#bspc config normal_border_color "#21202e"

#Atom one dark

bspc config focused_border_color "#4d9fe2"
bspc config active_border_color "#23262E"
bspc config presel_feedback_color "#b665cf"
bspc config normal_border_color "#21202e"




bspc config borderless_monocle   true
bspc config gapless_monocle     true
bspc config paddingless_monocle true
#bspc config single_monocle false

bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
# fix pointer
xsetroot -cursor_name left_ptr

# workspace 1 (Terminals)
declare -a terminal=(Alacritty Xfce4-terminal)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(discord)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Thunar Pcmanfm qBittorrent)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Steam)
declare -a office=(Steam)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=off; done

# workspace 5 (Media)
declare -a media=(vlc obs discord zoom lxmusic Gimp Gimp-2.10 \
)
for i in ${media[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

#workspace 6 (virtualization)
declare -a virtual=("VirtualBox Manager" Vmware)
for i in ${virtual[@]}; do
    bspc rule -a $i desktop='^6' follow=on focus=on; done

#workspace 6 (music)
#declare -a music=(Spotify)
#for i in ${music[@]}; do
#    bspc rule -a $i desktop='^7' follow=on focus=on; done




# bspc rule -a steam desktop=$urDesktopName follow=no


# workspace 8 (Settings)
declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr \
Pavucontrol Xfce4-settings-manager)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
declare -a floats=( splash pcsx2-qt Alafloat Lxappearance Arandr \ steam_app_1182480 Steam zoom Gnome-calculator Cpupower-gui Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad "Sign in - Google Accounts - Brave")
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done


bspc rule -a steam_app_1182480 state=floating


setxkbmap -layout us,latam -option grp:shifts_toggle

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey eww

# Launch Conky
sed -i "s/colors\/color-.*/colors\/color-tokyo.yuck\")/g" $HOME/.config/conkeww/eww.yuck
eww --config $HOME/.config/conkeww/ open conkeww-main

# Launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &


# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

nm-applet &
#change wallpaper
nitrogen --restore &

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# start flameshot
flameshot &

# start dropbox
dropbox start &

# start clipboard deamon
greenclip daemon &




picom --experimental-backends --blur-method dual_kawase --blur-strength 7 &

#picom --experimental-backends --animations &start compositor
#while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
#picom --config $HOME/.config/bspwm/picom.conf &


# steam -silent &
# replace neovim colorscheme
sed -i "s/theme =.*$/theme = \"tokyonight\",/g" $HOME/.config/nvim/lua/custom/chadrc.lua

# change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal"
cp "$XFCE_TERM_PATH"/colorschemes/tokyo-night "$XFCE_TERM_PATH"/terminalrc
