#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/bspwm/bin/launchbar.sh

## 144HZ configuration
bspc config pointer_motion_interval 7

## emulates i3 gaps' smart gaps config
bspc config single_monocle true
bspc config gapless_monocle true






bspc rule -a Pennywise state=floating sticky

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '漣'
		let name++
	done
}

workspaces

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}



bspc config border_width         2
bspc config window_gap           6
bspc config split_ratio          0.50

# bspc config focused_border_color "#7aa2f7"
# bspc config normal_border_color "#32344a"
# bspc config active_border_color "#444b6a"

bspc config active_border_color "#edecee"
bspc config focused_border_color "#61ffca"
bspc config presel_feedback_color "#6272a4"
bspc config normal_border_color "#21202e"


#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"
#bspc config presel_feedback_color "#6272a4"
#bspc config normal_border_color "#44475a"

bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle true
#bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# workspace 1 (Terminals)
declare -a terminal=(Alacritty Xfce4-terminal)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(firefox brave-browser discord)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Thunar dolphin Pcmanfm qBittorrent)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Steam)
declare -a office=(Steam)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=off; done

# workspace 5 (Media)
declare -a media=(vlc obs mpv discord zoom mplayer lxmusic Gimp Gimp-2.10 \
"VirtualBox Manager")
for i in ${media[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done


#workspace 6 (music)
declare -a music=(Spotify)
for i in ${music[@]}; do
    bspc rule -a $i desktop='^6' follow=on focus=on; done



# bspc rule -a steam desktop=$urDesktopName follow=no


# workspace 7 (Settings)
declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr \
Pavucontrol Xfce4-settings-manager)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \ steam_app_1182480 Steam zoom Gnome-calculator Cpupower-gui Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad "Sign in - Google Accounts - Brave")
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done


bspc rule -a steam_app_1182480 state=floating


setxkbmap -layout us,latam -option grp:shifts_toggle

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey eww

# Launch Conkeww
sed -i "s/colors\/color-.*/colors\/color-tokyo.yuck\")/g" $HOME/.config/conkeww/eww.yuck
eww --config $HOME/.config/conkeww/ open conkeww-main

# Launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &


# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

nm-applet &
#change wallpaper
nitrogen --restore &

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &


# start flameshot
flameshot &

# start dropbox
dropbox start &


# start clipboard deamon  
greenclip daemon &




picom --experimental-backends --blur-method dual_kawase --blur-strength 5 & 

# start compositor
#while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
#picom --config $HOME/.config/bspwm/picom.conf &

# replace neovim colorscheme
sed -i "s/theme =.*$/theme = \"tokyonight\",/g" $HOME/.config/nvim/lua/custom/chadrc.lua

# change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal"
cp "$XFCE_TERM_PATH"/colorschemes/tokyo-night "$XFCE_TERM_PATH"/terminalrc
